# config.py
BINANCE_API_KEY = "BINANCE_API_KEY_PLACEHOLDER"
BINANCE_API_SECRET = "BINANCE_SECRET_KEY_PLACEHOLDER"

KRAKEN_API_KEY = "KRAKEN_API_KEY_PLACEHOLDER"
KRAKEN_API_SECRET = "KRAKEN_SECRET_KEY_PLACEHOLDER"